spring:
    sql:
        init:
            mode: never #TODO: change if necessary
            data-locations: classpath:db/import.sql
    datasource:
        password: password
        url: jdbc:postgresql://localhost:5432/database?connectTimeout=30&socketTimeout=30
        username: postgres
    jpa:
        show-sql: true
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
    kafka:
        bootstrap-servers: localhost:9092
        partitions-quantity: 1
        replication-factor: 1
        properties:
            security:
                protocol: PLAINTEXT