spring:
    datasource:
        password: ${DB_PASS}
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?connectTimeout=30&socketTimeout=30
        username: ${DB_USER}
    kafka:
        bootstrap-servers: ''
        replicas: 1
