apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${{values.component_name}}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${{values.component_name}}
  minReplicas: _MIN_REPLICAS_
  maxReplicas: _MAX_REPLICAS_
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: _TARGET_CPU_

