apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-module
  title: App Module for Main App
  description: Create a typescript module for the main app
  tags:
    - recommended
    - typescript
spec:
  owner: bastian.hernandez@tenpo.cl
  type: module

  parameters:
    - title: Provide some simple information
      required:
        - moduleName
        - moduleNameNexus
      properties:
        moduleName:
          title: Module name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        moduleNameNexus:
          title: Module name on Nexus server
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - gitlab.com

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          component_name: ${{ parameters.moduleName }}

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        allowedHosts: ["gitlab.com"]
        description: This is ${{ parameters.moduleName }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}