apiVersion: v1
kind: Service
metadata:
  name: ${{values.component_name}}
  namespace: ${{values.namespace}}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "_INTERNAL_BALANCER_"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ${{values.component_name}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{values.component_name}}-ing-internal
  namespace: ${{values.namespace}}
spec:
  ingressClassName: kong-ingress-private
  rules:
    - host: _INGRESS_PRIVATE_HOST_
      http:
        paths:
          #TODO: replace this for your purpose
          - path: /${{values.component_name}}/v1/hello
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${{values.component_name}}
                port:
                  number: 80