apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_name}}
  description: ${{values.description}}
  annotations:
    backstage.io/techdocs-ref: dir:.

spec:
  type: service
  lifecycle: production
  owner:  ${{values.group_owner}}
  system: ${{values.flow_name}}